// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Airdrop$Type } from "./Airdrop";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Airdrop"]: Airdrop$Type;
    ["contracts/Airdrop.sol:Airdrop"]: Airdrop$Type;
  }
}
