// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IIcoController$Type } from "./IIcoController";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IIcoController"]: IIcoController$Type;
    ["contracts/interfaces/IIcoController.sol:IIcoController"]: IIcoController$Type;
  }
}
