// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IAirdrop$Type } from "./IAirdrop";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IAirdrop"]: IAirdrop$Type;
    ["contracts/interfaces/IAirdrop.sol:IAirdrop"]: IAirdrop$Type;
  }
}
