// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IAirdrop$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IAirdrop",
  "sourceName": "contracts/interfaces/IAirdrop.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address[]",
          "name": "beneficiaries",
          "type": "address[]"
        },
        {
          "internalType": "uint256[]",
          "name": "amounts",
          "type": "uint256[]"
        }
      ],
      "name": "batchSetAllowance",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "claim",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "target",
          "type": "address"
        }
      ],
      "name": "getClaimableAmount",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "beneficiary",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "setAllowance",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IAirdrop",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IAirdrop$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/interfaces/IAirdrop.sol:IAirdrop",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IAirdrop$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IAirdrop",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IAirdrop$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/interfaces/IAirdrop.sol:IAirdrop",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IAirdrop$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IAirdrop",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IAirdrop$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/interfaces/IAirdrop.sol:IAirdrop",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IAirdrop$Type["abi"]>>;
}
