// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IcoController$Type } from "./IcoController";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IcoController"]: IcoController$Type;
    ["contracts/IcoController.sol:IcoController"]: IcoController$Type;
  }
}
